Add unit and integration test environment
SAP/cf-service-operator pull request #44
Opened 2024-03-22 13:04 UTC by uwefreidank

This PR introduces a test framework for unit test and integration tests.
To prove it first unit test `binding_test` and first integration `space_controller_integration_test` have been added.
For integration test the `counterfeiter` module is used (like e.g. in https://github.com/SAP/sap-btp-service-operator)

Additional:
In order to satisfy the github.com default runner ubuntu-latest in my forked repo, the build workflow needed to be slightly adapted.

2024-03-25 14:45 UTC, TheBigElmo commented on .github/workflows/build.yaml
> +    runs-on: ubuntu-latest
we only use specific versions and will update it, once the new LTS version was released and tested.

2024-03-25 14:47 UTC, TheBigElmo commented on Meeting with Owner.md
Please remove internal communications

2024-03-25 15:03 UTC, TheBigElmo commented
I have updated the year for the license header. https://github.com/SAP/cf-service-operator/commit/52a5fec2c31509a45ddab40007a015fce1bfed06

2024-03-25 15:08 UTC, uwefreidank commented
should we have a separate PR, only for updating the year in the license header of all files, as the test pipeline complains about several files.
But i don't want to mix up this with the actual test-introduction.

2024-03-25 15:24 UTC, uwefreidank commented
Let's first merge https://github.com/SAP/cf-service-operator/pull/45 to make the build pipeline happy.

2024-03-25 17:18 UTC, cbarbian-sap commented
Thanks for contributing. Just to understand - what is the purpose of the new `State` type and according constants? It's not used, is it?

2024-03-26 11:56 UTC, uwefreidank commented on Dockerfile
> + && netstat -a | grep 8080 \
unfortunately the build pipeline fails https://github.com/SAP/cf-service-operator/actions/runs/8435429658/job/23100858286
we need to figure out, how to satisfy the docker build step.

2024-03-26 12:47 UTC, uwefreidank commented on Dockerfile
> + && netstat -a | grep 8080 \
is there a reason, why we need to run the test within the dockerfile, @cbarbian-sap ?
the `build-docker` job needs the `test`job anyway.
seems that port 8080 is already in use, and let the envtest fail.

2024-03-26 12:49 UTC, cbarbian-sap commented on Dockerfile
> + && netstat -a | grep 8080 \
Not sure about the root cause of the bind error; either the test somehow starts up multiple controllers in parallel or does not shut them down when done (don't think so actually), or it clashes with something already running on the github runner on 8080; we usually disable metrics/health endpoints in envtest, such as here: https://github.com/SAP/redis-operator/blob/main/pkg/operator/operator_suite_test.go#L112

2024-03-26 13:08 UTC, uwefreidank commented on Dockerfile
> + && netstat -a | grep 8080 \
thxs. the metrics endpoint is now also disabled. only question, why we need a test execution during build step.

2024-03-27 07:10 UTC, uwefreidank commented
@TheBigElmo @cbarbian-sap can we merge the PR?

2024-03-27 08:31 UTC, TheBigElmo requested changes
Please enable go test in the dockerfile, so it can be ensured, that the test works in this environment.

2024-03-27 09:14 UTC, TheBigElmo approved these changes

2024-03-27 12:46 UTC, merged