Improve log message
SAP/cf-service-operator pull request #56
Opened 2024-07-12 14:08 UTC by RalfHammer

Improve log message

TODO

2024-07-17 09:10 UTC, santiago-ventura submitted a review, later dismissed

2024-07-17 09:19 UTC, uwefreidank submitted a review, later dismissed

2024-07-18 09:44 UTC, TheBigElmo requested changes

2024-07-18 09:44 UTC, TheBigElmo commented on Makefile
Can you clean it up please?

2024-07-18 16:44 UTC, TheBigElmo approved these changes

2024-07-18 16:44 UTC, merged